<?php
/**
 * Dc_Regions
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Dc
 * @package    Dc_Regions
 * @copyright  Copyright (c) 2014-2015 Damián Culotta. (http://www.damianculotta.com.ar/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3 class="icon-head head-adminhtml-manager"><?php echo $this->getHeaderText(); ?></h3>
            </td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml(); ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <div>
        <form name="form" id="regions_installer_form" action="<?php echo $this->getSaveUrl(); ?>" method="post" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Install Regions') ?></h4>
            </div>
            <div id="base_fieldset" class="fieldset fieldset-wide">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label">
                                    <label for="country_id"><?php echo $this->__('Select Country'); ?> <span class="required">*</span></label>
                                </td>
                                <td class="value">
                                    <select name="country_id" class="input-text required-entry" id="country_id">
                                        <?php foreach ($this->getCountries() as $country_code => $country_name): ?>
                                            <option value="<?php echo $country_code; ?>"><?php echo $country_name; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" class="label">
                                    <?php echo $this->getButtonHtml($this->__('Install'), "this.form.submit()") ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
        <script type="text/javascript">
            var regions_installer_form = new varienForm('regions_installer_form');
        </script>
    </div>
</div>
